spring.application.name=MassiveFileProcessor

server.port=8080

# Configuración de archivos
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

# Logging
logging.level.com.massivefileprocessor=DEBUG

# Directorio temporal
#java.io.tmpdir=/tmp
